config/routes.rb
Rails.application.routes.draw do
   root 'messages#index'
   resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
    #名前は必須＆＆20文字以内
    validates :name, length:{ maximum: 20} , presence: true
    #内容は必須＆＆2文字以上3030文字以下
    validates :body, length:{ minimum: 2, maximum: 30} , presence: true
    #年齢は数字のみ入力可、0以上
    validates :age, numericality: {only_integer: true, greater_than_or_equal_to: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy] #set_messageメゾッドをedit,update,destroy前に行う処理
  def index
    #Message を全て取得する。
    @messages = Message.all
    @message = Message.new
  end
  
  def edit
    #editアクションでは、編集画面に来た時に実行されるアクションです。
    #中の実装は空ですが、フィルターの機能によって@messageが設定された状態でedit.html.erbをレンダリングします
  end
  
  def update
    #updateアクションではbefore_actionにより設定された@messageを用いて更新処理を実装しています
    if @message.update(message_params)
      #保存成功の場合topへリダイレクト
      redirect_to root_path, notice: 'メッセージを編集しました'
    else
      #保存に失敗
      render 'edit'
    end
  end
  
  def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end

##ここから記述
  def create
    @message = Message.new(message_params)
   if @message.save
    redirect_to root_path , notice: 'メッセージを保存しました'
   else
    #メッセージを保存できなかった時
    @messages = Message.all
    flash.now[:alert] = "メッセージの保存に失敗しました"
    render 'index'
   end
  end

##ここから下はprivateメゾッド
  private
  def message_params
    #params[:message]のパラメータでname, bodyのみ許可する
    #返り値はex:){name: "入力されたname" , body: "入力されたbody"}
    params.require(:message).permit(:name, :body, :age)
  end
  
  def set_message
    @message = Message.find(params[:id])
  end
  ##ここまで
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=> true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
      <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Message Board</a>
      </div>
      <!-- navbar-header -->
    </div>
    <!-- container -->
  </nav>
  <div class="container">
    <% if notice %>
     <div class="alert alert-info">
       <%= notice %>
     </div>
    <% end %>
    
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<div class="form-horizontal" role="form">
    <%= form_for(@message) do |f| %>
        <% if @message.errors.present? %>
            <div class="alert alert-danger">
                <% alert %>
                <ul>
                    <% @message.errors.full_messages.each do |full_message| %>
                    <li>
                        <%= full_message %>
                    </li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        <div class="form-group">
            <%= f.label :名前：, class: "col-sm-3 control-label" %>
            <div class="col-sm-7">
                <%= f.text_field :name , class: "form-control"%>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :内容：, class: "col-sm-3 control-label" %>
            <div class="col-sm-7">
                <%= f.text_field :body, class: "form-control"%>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :年齢：, class: "col-sm-3 control-label" %>
            <div class="col-sm-7">
                <%= f.text_field :age , class: "form-control"%>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-5 col-sm-12">
                <%= f.submit class: "btn btn-sm btn-primary" %>
            </div>
        </div>
    <% end %>
</div>

app/views/messages/edit.html.erb
<h1>メッセージの編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<!-- <h1>Messages#index</h1> -->
<!-- <p>Find me in app/views/messages/index.html.erb</p> -->
<div class="panel panel-default">
    <div class="panel-heading">
     メッセージ一覧
    </div>

    <div class="panel-body">
        <% @messages.each do |message| %>
         <span class="label label-info"><%= message.name %></span>
            <%= message.body %>
            ( <%= message.age %>歳)
            [ <%= link_to "edit" , edit_message_path(message), class: "btn btn-xs btn-success" %>
             <%= link_to "destroy", message , method: :delete , data: { confirm:'削除してもよろしいですか？'}, class: "btn btn-xs btn-danger" %>
             ]
            <br>
        <% end %>
    </div>
</div>

<% #部分テンプレート読み込み %>
<%= render 'form' %>